<?php
    return[
        'public'=>[
            'css'=>['Admin/bootstrap.min.css','Admin/bootstrap-datetimepicker.min.css'],
            'js'=>['Admin/jquery-1.12.4.min.js','Admin/bootstrap.min.js','Admin/bootstrap-datetimepicker.min.js','Admin/modify_password.js','Admin/nav.js']
        ],
        'welcome'=>[
            'css'=>['Admin/welcome.css'],
        ],
        '/'=>[
            'css'=>['Admin/login.css'],
            'js'=>['Admin/login.js']
        ],
        'project_index'=>[
            'css'=>['Admin/project_index.css'],
            'js'=>['Admin/project_index.js']
        ],
        'finance_index'=>[
            'css'=>['Admin/finance_index.css'],
            'js'=>['Admin/finance_index.js']
        ],
        'expenditure_index'=>[
            'css'=>['Admin/expenditure_index.css'],
            'js'=>['Admin/expenditure_index.js','Admin/jquery.form.js']
        ],
        'contract_index'=>[
            'css'=>['Admin/contract_index.css'],
            'js'=>['Admin/contract_index.js','Admin/jquery.form.js']
        ],
        'admin_index'=>[
            'css'=>['Admin/admin_index.css'],
            'js'=>['Admin/admin_index.js']
        ],
        'customer_index'=>[
            'css'=>['Admin/customer_index.css'],
            'js'=>['Admin/customer_index.js']
        ],
        'menu_list'=>[
            'css'=>['Admin/menu_list.css'],
            'js'=>['Admin/menu_list.js']
        ],
        'menu_cate_list'=>[
            'css'=>['Admin/menu_cate_list.css'],
            'js'=>['Admin/menu_cate_list.js']
        ],
        'role_index'=>[
            'css'=>['Admin/role_index.css'],
            'js'=>['Admin/role_index.js']
        ],
        'power_index'=>[
            'css'=>['Admin/power_index.css'],
            'js'=>['Admin/power_index.js']
        ],
        'step_index'=>[
            'css'=>['Admin/step_index.css'],
            'js'=>['Admin/step_index.js']
        ],
        'type_index'=>[
            'css'=>['Admin/type_index.css'],
            'js'=>['Admin/type_index.js']
        ],
        'wages_index'=>[
            'css'=>['Admin/wages_index.css'],
            'js'=>['Admin/wages_index.js']
        ],
    ];